version: "3.2"

services:
  rabbitmq:
    container_name: 'rabbitmq'
    hostname: rabbitmq
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge